# Generated by Django 5.1.1 on 2024-09-09 03:47

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('stock', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, validators=[main.models.validate_rating])),
            ],
        ),
    ]
